[package]
name = "hackernews-embs2ndjson"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytemuck = "1.16.1"
clap = { version = "4.5.8", features = ["derive"] }
memmap2 = "0.9.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
